(function () {
  const copy = {
    en: {
      top: ["PRODUCT FINDER", "Use the official manufacturer range to choose. EST handles the export quotation and consolidation."],
      nav: ["Brand Partners", "Product Finder", "Official Catalogues", "Process", "Contact"],
      hero: ["SELECT A PRODUCT FAMILY", "Japanese materials, specified by code and quoted for export.", "We are a distributor and export partner, not the manufacturer. Product ranges, colours and model numbers remain on the official Japanese sites so your team always works from the current source. Send us a model code, URL or screenshot and we will return availability, export price, lead time and the applicable documentation.", ["OFFICIAL RANGE LINKS", "MULTI-BRAND CONSOLIDATION", "FCL / LCL SHIPPING"]],
      section: ["PRODUCT FAMILIES", "Start with the material you need.", "These are the high-intent product groups most often specified by overseas developers, importers, distributors and hospitality fit-out teams. This page is a buying guide, not a static copy of each manufacturer’s catalogue."],
      cards: [["Kitchens & Housing Equipment", "System kitchens, worktops, storage, washrooms and related housing equipment for residential and hospitality projects.", "Browse LIXIL range ↗", "Browse Panasonic ↗"], ["Bathrooms & Washrooms", "Unit bathrooms, vanities, toilets and faucets. Confirm the module and rough opening before requesting a final quotation.", "Browse LIXIL range ↗", "Browse Panasonic ↗"], ["Flooring", "Engineered wood, vinyl sheet, LVT, carpet tile and related interior flooring for residential and commercial use.", "Browse TOLI range ↗", "Browse DAIKEN ↗"], ["Wallcovering & Decorative Film", "Contract wallcovering, decorative film, non-woven and fabric-backed finishes. Japanese rolls and fire classifications require project-specific checking.", "Browse Sangetsu range ↗", "Send a product request →"], ["Interior Doors & Storage", "Hinged and sliding door sets, frames, casing and storage units. We confirm the complete assembly and opening dimensions together.", "Browse NODA range ↗", "Send a product request →"], ["Boards, Ceiling & Acoustic Systems", "Gypsum, fire-rated, moisture-resistant and acoustic board lines for projects that need documentation by line item.", "Browse Chiyoda Ute ↗", "Send a product request →"]],
      callout: ["Have a model number already?", "Send the code, official page URL or a screenshot with your destination port and estimated quantity. We will check the export route and quote it with other brands in the same shipment.", "Request a quotation →"],
      fine: ["Material and brand note.", "EST Co., Ltd. is a distributor/export partner. Manufacturer names, trademarks, product images and technical data belong to their respective owners. Official range links open the relevant manufacturer site; availability, export eligibility, price and certification are confirmed per enquiry."],
      footer: ["© 2026 EST Co., Ltd.", "Tokyo, Japan · nana@jpbuildest.com"]
    },
    zh: {
      top: ["产品选型", "请从制造商官方系列中选择，EST 负责出口报价与合并装柜。"], nav: ["品牌合作方", "产品选型", "官方图册", "合作流程", "联系我们"],
      hero: ["选择产品系列", "按型号选定日本建材，统一出口报价。", "我们是经销商和出口合作伙伴，并非制造商。产品系列、颜色和型号以制造商日本官网为准，让您的团队始终使用最新源头资料。发送型号、网址或截图，我们会返回可供性、出口价格、交期和适用资料。", ["官方系列链接", "多品牌合并采购", "整柜 / 拼柜运输"]],
      section: ["产品系列", "从您需要的材料开始。", "这些是海外开发商、进口商、经销商和酒店室内项目最常指定的产品组。本页是采购指南，不是制造商图册的静态复制。"],
      cards: [["厨房与住宅设备", "整体厨房、台面、收纳、洗面和相关住宅设备，适用于住宅与酒店项目。", "浏览 LIXIL 系列 ↗", "浏览 Panasonic ↗"], ["浴室与洗面空间", "整体浴室、洗面台、坐便器和龙头。申请最终报价前，请确认模数与洞口尺寸。", "浏览 LIXIL 系列 ↗", "浏览 Panasonic ↗"], ["地板与地材", "工程木、卷材、LVT、方块地毯及相关室内地材，适用于住宅与商业项目。", "浏览 TOLI 系列 ↗", "浏览 DAIKEN ↗"], ["壁纸与装饰膜", "工程级壁纸、装饰膜、无纺和布基饰面。日本卷材尺寸与防火分类需按项目核对。", "浏览 Sangetsu 系列 ↗", "提交产品需求 →"], ["室内门与收纳", "平开和推拉门套、门框、套线与收纳单元。我们会一起确认完整组合与洞口尺寸。", "浏览 NODA 系列 ↗", "提交产品需求 →"], ["板材、吊顶与吸音系统", "石膏板、防火、防潮和吸音板材，适用于需要逐项资料的项目。", "浏览 Chiyoda Ute ↗", "提交产品需求 →"]],
      callout: ["已经有型号了吗？", "发送型号、官方页面或截图，并附目的港和预计数量。我们会核对出口路径，并与其他品牌合并报价。", "申请报价 →"], fine: ["材料与品牌说明。", "EST 株式会社是经销商和出口合作伙伴。制造商名称、商标、产品图片和技术数据归各自权利人所有。官方链接会打开制造商网站；可供性、出口资格、价格和认证按询价逐项确认。"], footer: ["© 2026 EST 株式会社", "东京，日本 · nana@jpbuildest.com"]
    },
    hi: {
      top: ["उत्पाद चयन", "चयन के लिए निर्माता की आधिकारिक रेंज देखें। EST निर्यात कोटेशन और समेकन संभालता है।"], nav: ["ब्रांड पार्टनर", "उत्पाद चयन", "आधिकारिक कैटलॉग", "प्रक्रिया", "संपर्क"],
      hero: ["उत्पाद श्रृंखला चुनें", "कोड के आधार पर जापानी सामग्री चुनें और निर्यात कोटेशन पाएं।", "हम निर्माता नहीं, वितरक और निर्यात भागीदार हैं। रेंज, रंग और मॉडल नंबर आधिकारिक जापानी साइटों पर रहते हैं। मॉडल कोड, URL या स्क्रीनशॉट भेजें; हम उपलब्धता, निर्यात मूल्य, समय और लागू दस्तावेज़ लौटाएंगे।", ["आधिकारिक रेंज लिंक", "मल्टी-ब्रांड समेकन", "FCL / LCL शिपिंग"]],
      section: ["उत्पाद परिवार", "अपनी आवश्यक सामग्री से शुरू करें।", "ये वे उत्पाद समूह हैं जिन्हें विदेशी डेवलपर, आयातक, वितरक और हॉस्पिटैलिटी प्रोजेक्ट अक्सर चुनते हैं। यह खरीद गाइड है, निर्माता कैटलॉग की प्रतिलिपि नहीं।"],
      cards: [["किचन और हाउसिंग उपकरण", "सिस्टम किचन, वर्कटॉप, स्टोरेज, वॉशरूम और संबंधित उपकरण।", "LIXIL रेंज देखें ↗", "Panasonic देखें ↗"], ["बाथरूम और वॉशरूम", "यूनिट बाथ, वैनिटी, टॉयलेट और नल। अंतिम कोटेशन से पहले मॉड्यूल और ओपनिंग जांचें।", "LIXIL रेंज देखें ↗", "Panasonic देखें ↗"], ["फ्लोरिंग", "इंजीनियर्ड वुड, विनाइल शीट, LVT, कारपेट टाइल और संबंधित फर्श सामग्री।", "TOLI रेंज देखें ↗", "DAIKEN देखें ↗"], ["वॉलकवरिंग और सजावटी फिल्म", "कॉन्ट्रैक्ट वॉलकवरिंग, सजावटी फिल्म और फैब्रिक-बैक्ड फिनिश। जापानी रोल और फायर वर्गीकरण की परियोजना-विशिष्ट जांच जरूरी है।", "Sangetsu रेंज देखें ↗", "उत्पाद अनुरोध भेजें →"], ["इंटीरियर दरवाज़े और स्टोरेज", "हिंग्ड और स्लाइडिंग दरवाज़ा सेट, फ्रेम, चौखट और स्टोरेज यूनिट। पूर्ण संयोजन और ओपनिंग साथ में जांचते हैं।", "NODA रेंज देखें ↗", "उत्पाद अनुरोध भेजें →"], ["बोर्ड, सीलिंग और ध्वनि प्रणालियां", "जिप्सम, अग्नि-रोधक, नमी-रोधक और ध्वनि-रोधक बोर्ड, लाइन-आइटम दस्तावेज़ के साथ।", "Chiyoda Ute देखें ↗", "उत्पाद अनुरोध भेजें →"]],
      callout: ["क्या मॉडल नंबर तैयार है?", "कोड, आधिकारिक URL या स्क्रीनशॉट के साथ गंतव्य पोर्ट और अनुमानित मात्रा भेजें। हम निर्यात मार्ग जांचकर अन्य ब्रांडों के साथ कोटेशन देंगे।", "कोटेशन मांगें →"], fine: ["सामग्री और ब्रांड नोट।", "EST Co., Ltd. वितरक और निर्यात भागीदार है। निर्माता नाम, ट्रेडमार्क, उत्पाद चित्र और तकनीकी डेटा संबंधित स्वामियों के हैं। उपलब्धता, निर्यात पात्रता, मूल्य और प्रमाणन पूछताछ के अनुसार पुष्टि किए जाते हैं।"], footer: ["© 2026 EST Co., Ltd.", "टोक्यो, जापान · nana@jpbuildest.com"]
    },
    es: {
      top: ["SELECTOR DE PRODUCTOS", "Elija en la gama oficial del fabricante. EST gestiona el presupuesto de exportación y la consolidación."], nav: ["Marcas asociadas", "Selector de productos", "Catálogos oficiales", "Proceso", "Contacto"],
      hero: ["SELECCIONE UNA FAMILIA DE PRODUCTOS", "Materiales japoneses, seleccionados por código y presupuestados para exportación.", "Somos distribuidores y socios de exportación, no el fabricante. Las gamas, colores y códigos permanecen en los sitios oficiales japoneses. Envíenos el código, URL o captura y devolveremos disponibilidad, precio de exportación, plazo y documentación aplicable.", ["ENLACES OFICIALES", "CONSOLIDACIÓN MULTIMARCA", "ENVÍO FCL / LCL"]],
      section: ["FAMILIAS DE PRODUCTOS", "Empiece por el material que necesita.", "Estos son los grupos que más suelen especificar promotores, importadores, distribuidores y equipos hoteleros internacionales. Esta página es una guía de compra, no una copia del catálogo del fabricante."],
      cards: [["Cocinas y equipamiento de vivienda", "Cocinas modulares, encimeras, almacenaje, lavabos y equipamiento para vivienda y hotel.", "Ver gama LIXIL ↗", "Ver Panasonic ↗"], ["Baños y lavabos", "Baños modulares, muebles de lavabo, inodoros y grifería. Confirme el módulo y el hueco antes del presupuesto.", "Ver gama LIXIL ↗", "Ver Panasonic ↗"], ["Pavimentos", "Madera de ingeniería, vinilo, LVT, moqueta modular y suelos interiores para vivienda y comercio.", "Ver gama TOLI ↗", "Ver DAIKEN ↗"], ["Revestimientos y film decorativo", "Revestimientos contract, film decorativo y acabados no tejidos o con soporte textil. Las medidas y clases de fuego japonesas requieren revisión por proyecto.", "Ver gama Sangetsu ↗", "Enviar solicitud →"], ["Puertas interiores y almacenaje", "Conjuntos abatibles y correderos, marcos, tapetas y unidades de almacenaje. Confirmamos el conjunto y el hueco conjuntamente.", "Ver gama NODA ↗", "Enviar solicitud →"], ["Paneles, techos y acústica", "Placas de yeso, paneles ignífugos, resistentes a la humedad y acústicos, con documentación por partida.", "Ver Chiyoda Ute ↗", "Enviar solicitud →"]],
      callout: ["¿Ya tiene un código de modelo?", "Envíe el código, la URL oficial o una captura junto con el puerto de destino y la cantidad estimada. Comprobaremos la ruta de exportación y lo cotizaremos con otras marcas.", "Solicitar cotización →"], fine: ["Nota sobre materiales y marcas.", "EST Co., Ltd. es distribuidor y socio de exportación. Los nombres, marcas, imágenes y datos técnicos pertenecen a sus respectivos titulares. La disponibilidad, elegibilidad de exportación, precio y certificación se confirman por consulta."], footer: ["© 2026 EST Co., Ltd.", "Tokio, Japón · nana@jpbuildest.com"]
    },
    fr: {
      top: ["SÉLECTEUR DE PRODUITS", "Choisissez dans la gamme officielle du fabricant. EST gère le devis export et la consolidation."], nav: ["Marques partenaires", "Sélecteur de produits", "Catalogues officiels", "Processus", "Contact"],
      hero: ["CHOISIR UNE GAMME DE PRODUITS", "Matériaux japonais, sélectionnés par code et chiffrés pour l’export.", "Nous sommes distributeur et partenaire export, pas le fabricant. Les gammes, couleurs et références restent sur les sites japonais officiels. Envoyez le code, l’URL ou une capture ; nous confirmerons disponibilité, prix export, délai et documents applicables.", ["LIENS DE GAMMES OFFICIELLES", "CONSOLIDATION MULTIMARQUE", "EXPÉDITION FCL / LCL"]],
      section: ["GAMMES DE PRODUITS", "Commencez par le matériau dont vous avez besoin.", "Voici les familles les plus souvent spécifiées par les promoteurs, importateurs, distributeurs et équipes hôtelières internationales. Cette page est un guide d’achat, pas une copie du catalogue fabricant."],
      cards: [["Cuisines et équipements résidentiels", "Cuisines, plans de travail, rangements, lavabos et équipements pour résidentiel et hôtellerie.", "Voir la gamme LIXIL ↗", "Voir Panasonic ↗"], ["Salles de bains et lavabos", "Salles de bains modulaires, meubles vasque, toilettes et robinetterie. Confirmez le module et la réservation avant devis.", "Voir la gamme LIXIL ↗", "Voir Panasonic ↗"], ["Revêtements de sol", "Bois techniques, vinyle, LVT, dalles de moquette et sols intérieurs pour résidentiel et commerce.", "Voir la gamme TOLI ↗", "Voir DAIKEN ↗"], ["Revêtements muraux et film décoratif", "Revêtements contract, films décoratifs et finitions non tissées ou textiles. Les formats et classements feu japonais doivent être vérifiés par projet.", "Voir la gamme Sangetsu ↗", "Envoyer une demande →"], ["Portes intérieures et rangement", "Ensembles battants et coulissants, huisseries, chambranles et rangements. Nous confirmons l’ensemble et la réservation ensemble.", "Voir la gamme NODA ↗", "Envoyer une demande →"], ["Panneaux, plafonds et acoustique", "Plaques de plâtre, panneaux coupe-feu, hydrofuges et acoustiques, avec documentation par article.", "Voir Chiyoda Ute ↗", "Envoyer une demande →"]],
      callout: ["Vous avez déjà une référence ?", "Envoyez le code, l’URL officielle ou une capture avec le port de destination et la quantité estimée. Nous vérifierons la route export et chiffrerons avec les autres marques.", "Demander un devis →"], fine: ["Note matériaux et marques.", "EST Co., Ltd. est distributeur et partenaire export. Les noms, marques, images et données techniques appartiennent à leurs titulaires respectifs. Disponibilité, éligibilité export, prix et certification sont confirmés sur demande."], footer: ["© 2026 EST Co., Ltd.", "Tokyo, Japon · nana@jpbuildest.com"]
    }
  };

  const setText = (el, value) => {
    if (!el || value === undefined) return;
    if (!el.dataset.originalText) el.dataset.originalText = el.textContent;
    el.textContent = value;
  };
  const setProductLanguage = lang => {
    const c = copy[lang] || copy.en;
    document.documentElement.lang = lang;
    setText(document.querySelector('.top b'), c.top[0]); setText(document.querySelector('.top span'), c.top[1]);
    [...document.querySelectorAll('.nav a')].forEach((el, i) => setText(el, c.nav[i]));
    setText(document.querySelector('.hero .eyebrow'), c.hero[0]); setText(document.querySelector('.hero h1'), c.hero[1]); setText(document.querySelector('.hero p'), c.hero[2]);
    [...document.querySelectorAll('.hero-note .pill')].forEach((el, i) => setText(el, c.hero[3][i]));
    setText(document.querySelector('.section > .wrap > .eyebrow'), c.section[0]); setText(document.querySelector('.section h2'), c.section[1]); setText(document.querySelector('.section-intro'), c.section[2]);
    [...document.querySelectorAll('.card')].forEach((card, i) => { const x = c.cards[i]; setText(card.querySelector('h3'), x[0]); setText(card.querySelector('.body p'), x[1]); [...card.querySelectorAll('.actions a')].forEach((el, j) => setText(el, x[j + 2])); });
    setText(document.querySelector('.callout h3'), c.callout[0]); setText(document.querySelector('.callout p'), c.callout[1]); setText(document.querySelector('.callout a'), c.callout[2]);
    const fine = document.querySelector('.fine .wrap'); if (fine) { if (!fine.dataset.originalText) fine.dataset.originalText = fine.textContent; fine.textContent = c.fine[0] + ' ' + c.fine[1]; }
    [...document.querySelectorAll('footer .wrap span')].forEach((el, i) => setText(el, c.footer[i]));
    document.getElementById('langToggle').value = lang;
    const url = new URL(window.location.href); url.searchParams.set('lang', lang); history.replaceState(null, '', url);
    document.querySelectorAll('a[href^="index.html"]').forEach(link => {
      const target = new URL(link.getAttribute('href'), window.location.href);
      target.searchParams.set('lang', lang);
      link.href = target.pathname.split('/').pop() + target.search + target.hash;
    });
  };
  document.getElementById('langToggle').addEventListener('change', e => setProductLanguage(e.target.value));
  const requestedLang = new URLSearchParams(window.location.search).get('lang');
  setProductLanguage(copy[requestedLang] ? requestedLang : 'en');
})();
